# Save Configuration
moving average step: 2000
save model frequency: 40960
save statistic frequency: 2000
save image frequency: 2000

# Model Configuration
frame stack: 4
single network: True
shared SF: False

# Training Configuration
gamma: 0.99
lambda: 0.95
minibatch size: 128
epoch: 4
buffer size: 2048
drop remainder: True
decentral learning rate: 0.0001
central learning rate: 0.0010
eps: 0.20
target_kl: 0.015
entropy beta: 0.01
psi beta: 0.5
reward beta: 0.0005
decoder beta: 0.0001
critic beta: 0.5
q beta: 0.005
learnability beta: 0.000

# Gradient
decentral gradient global norm: 50
central gradient global norm: 50

# Network Configuration
atoms: 128
central critic td lambda: True
central critic td standardize: False
decentral critic td lambda: True
decentral critic td standardize: True
advantage global norm: True

# Misc
reduction_sum: True
central critic encoder: 'hyper1'
decentral critic encoder: 'hyper1'
decentral pi encoder: 'basic'

update target interval: 200
